name: msa
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5=7_kmp_llvm
  - _python_abi3_support=1.0=hd8ed1ab_2
  - aom=3.9.1=h7bae524_0
  - appnope=0.1.4=pyhd8ed1ab_1
  - asttokens=3.0.1=pyhd8ed1ab_0
  - bzip2=1.0.8=h80987f9_6
  - c-ares=1.34.6=hc919400_0
  - ca-certificates=2025.12.2=hca03da5_0
  - cairo=1.18.0=hc6c324b_2
  - comm=0.2.3=pyhe01879c_0
  - cpython=3.12.12=py312hd8ed1ab_1
  - dav1d=1.2.1=hb547adb_0
  - debugpy=1.8.16=py312h50f4ffc_1
  - decorator=5.2.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.3=h50f4ffc_4
  - ffmpeg=7.1.0=gpl_h92f8dbd_105
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h1383a14_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - freetype=2.14.1=hce30654_0
  - fribidi=1.0.16=hc919400_0
  - gdk-pixbuf=2.42.12=h7ddc832_0
  - gmp=6.3.0=h7bae524_2
  - google-cloud-sdk=550.0.0=py312h81bd7bf_0
  - graphite2=1.3.14=hec049ff_2
  - harfbuzz=9.0.0=h1836168_0
  - hdf5=1.14.4=nompi_ha698983_105
  - icu=73.2=hc8870d7_0
  - imath=3.1.12=h025cafa_0
  - ipykernel=7.1.0=pyh5552912_0
  - ipython=9.8.0=pyh53cf698_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jasper=4.2.8=hc0e5025_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=8.7.0=pyhcf101f3_0
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - krb5=1.21.3=h237132a_0
  - lame=3.100=h1a8c8d9_1003
  - lerc=4.0.0=hd64df32_1
  - libabseil=20240722.0=cxx17_h07bc746_4
  - libaec=1.1.4=h51d1e36_0
  - libasprintf=0.25.1=h493aca8_0
  - libass=0.17.3=hf20b609_0
  - libblas=3.11.0=5_h51639a9_openblas
  - libcblas=3.11.0=5_hb0561ab_openblas
  - libcurl=8.17.0=hdece5d2_1
  - libcxx=20.1.8=hd7fd590_1
  - libdeflate=1.22=hd74edd7_0
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libev=4.33=h93a5062_2
  - libexpat=2.7.3=h50f4ffc_4
  - libffi=3.4.4=hca03da5_1
  - libfreetype=2.14.1=hce30654_0
  - libfreetype6=2.14.1=h6da58f4_0
  - libgcc=15.2.0=hcbb3090_16
  - libgettextpo=0.25.1=h493aca8_0
  - libgfortran=15.2.0=h07b0088_16
  - libgfortran5=15.2.0=hdae7583_16
  - libglib=2.84.0=hdff4504_0
  - libhwloc=2.12.1=default_h88f92a7_1000
  - libiconv=1.18=h23cfdf5_2
  - libintl=0.25.1=h493aca8_0
  - libjpeg-turbo=3.1.2=hc919400_0
  - liblapack=3.11.0=5_hd9741b5_openblas
  - liblapacke=3.11.0=5_h1b118fd_openblas
  - libnghttp2=1.67.0=hc438710_0
  - libopenblas=0.3.30=openmp_ha158390_3
  - libopencv=4.10.0=headless_py312h6c32981_12
  - libopenvino=2024.4.0=hbfeda7a_2
  - libopenvino-arm-cpu-plugin=2024.4.0=hbfeda7a_2
  - libopenvino-auto-batch-plugin=2024.4.0=hf276634_2
  - libopenvino-auto-plugin=2024.4.0=hf276634_2
  - libopenvino-hetero-plugin=2024.4.0=h03892cd_2
  - libopenvino-ir-frontend=2024.4.0=h03892cd_2
  - libopenvino-onnx-frontend=2024.4.0=h7f5a098_2
  - libopenvino-paddle-frontend=2024.4.0=h7f5a098_2
  - libopenvino-pytorch-frontend=2024.4.0=h5833ebf_2
  - libopenvino-tensorflow-frontend=2024.4.0=h9d544f2_2
  - libopenvino-tensorflow-lite-frontend=2024.4.0=h5833ebf_2
  - libopus=1.6=he530434_0
  - libpng=1.6.53=hfab5511_0
  - libprotobuf=5.28.2=h8f0b736_0
  - librsvg=2.58.4=h40956f1_0
  - libsodium=1.0.20=h99b78c6_0
  - libsqlite=3.51.1=h1b79a29_1
  - libssh2=1.11.1=h1590b86_0
  - libtiff=4.7.0=hfce79cd_1
  - libvpx=1.14.1=h7bae524_0
  - libwebp-base=1.6.0=h07db88b_0
  - libxml2=2.13.9=h528a072_0
  - libzlib=1.3.1=h5f15de7_0
  - llvm-openmp=21.1.8=h4a912ad_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - ncurses=6.5=hee39554_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - opencv=4.10.0=headless_py312h9042956_12
  - openexr=3.3.2=h04410fd_0
  - openh264=2.5.0=h774163f_0
  - openssl=3.6.0=h5503f6c_0
  - pango=1.54.0=h9ee27a3_2
  - parso=0.8.5=pyhcf101f3_0
  - pcre2=10.44=ha881caa_2
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pip=25.3=pyhc872135_0
  - pixman=0.46.4=h81086ad_1
  - platformdirs=4.5.1=pyhcf101f3_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.0.0=py312haa24f5a_1
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pugixml=1.14=h13dd4ca_0
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - py-opencv=4.10.0=headless_py312h014d1a3_12
  - pygments=2.19.2=pyhd8ed1ab_0
  - python=3.12.8=h89a136b_0_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-gil=3.12.12=hd8ed1ab_1
  - python_abi=3.12=3_cp312
  - pyzmq=27.1.0=py312hd65ceae_0
  - readline=8.3=h0b18652_0
  - setuptools=80.9.0=py312hca03da5_0
  - six=1.17.0=pyhe01879c_1
  - snappy=1.2.2=hada39a4_1
  - sqlite=3.51.0=hab6afd1_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - svt-av1=2.3.0=hf24288c_0
  - tbb=2022.3.0=h66ce52b_1
  - tk=8.6.15=hcd8a7d5_0
  - tornado=6.5.4=py312haa24f5a_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - wheel=0.45.1=py312hca03da5_0
  - x264=1!164.3095=h57fd34a_2
  - x265=3.5=hbc6ce65_3
  - xz=5.6.4=h80987f9_1
  - zeromq=4.3.5=h888dc83_9
  - zlib=1.3.1=h5f15de7_0
  - zstd=1.5.7=hbf9d68e_6
  - pip:
      - accelerate==1.12.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - altair==5.5.0
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - anthropic==0.75.0
      - anyio==4.12.0
      - attrs==25.4.0
      - backoff==2.2.1
      - bcrypt==5.0.0
      - blinker==1.9.0
      - bottleneck==1.6.0
      - cachetools==5.5.2
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - chroma-hnswlib==0.7.3
      - chromadb==0.4.15
      - click==8.3.1
      - coloredlogs==15.0.1
      - contourpy==1.3.3
      - cycler==0.12.1
      - dataclasses-json==0.6.7
      - datasets==4.4.2
      - db-dtypes==1.5.0
      - deprecated==1.3.1
      - diffusers==0.36.0.dev0
      - dill==0.4.0
      - distro==1.9.0
      - docstring-parser==0.17.0
      - durationpy==0.10
      - evaluate==0.4.6
      - fastapi==0.104.1
      - filelock==3.20.1
      - filetype==1.2.0
      - flatbuffers==25.12.19
      - fonttools==4.61.1
      - frozenlist==1.8.0
      - fsspec==2025.10.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - google-ai-generativelanguage==0.6.15
      - google-api-core==2.28.1
      - google-api-python-client==2.187.0
      - google-auth==2.45.0
      - google-auth-httplib2==0.3.0
      - google-auth-oauthlib==1.2.3
      - google-cloud-aiplatform==1.115.0
      - google-cloud-bigquery==3.30.0
      - google-cloud-core==2.5.0
      - google-cloud-resource-manager==1.15.0
      - google-cloud-storage==2.19.0
      - google-crc32c==1.8.0
      - google-genai==1.56.0
      - google-generativeai==0.8.6
      - google-resumable-media==2.8.0
      - googleapis-common-protos==1.72.0
      - greenlet==3.3.0
      - grpc-google-iam-v1==0.14.3
      - grpcio==1.76.0
      - grpcio-status==1.62.3
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httplib2==0.31.0
      - httptools==0.7.1
      - httpx==0.28.1
      - httpx-sse==0.4.3
      - huggingface-hub==0.36.0
      - humanfriendly==10.0
      - idna==3.11
      - importlib-metadata==6.11.0
      - importlib-resources==6.5.2
      - jinja2==3.1.6
      - jiter==0.12.0
      - joblib==1.5.3
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - kiwisolver==1.4.9
      - kubernetes==34.1.0
      - langchain==1.2.0
      - langchain-anthropic==1.3.0
      - langchain-classic==1.0.1
      - langchain-community==0.4.1
      - langchain-core==1.2.5
      - langchain-google-genai==4.1.2
      - langchain-google-vertexai==3.2.0
      - langchain-text-splitters==1.1.0
      - langgraph==1.0.5
      - langgraph-checkpoint==3.0.1
      - langgraph-prebuilt==1.0.5
      - langgraph-sdk==0.3.1
      - langsmith==0.5.1
      - llvmlite==0.46.0
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - marshmallow==3.26.2
      - matplotlib==3.10.8
      - mdurl==0.1.2
      - more-itertools==10.8.0
      - mpmath==1.3.0
      - msgpack==1.1.2
      - multidict==6.7.0
      - multiprocess==0.70.18
      - mypy-extensions==1.1.0
      - narwhals==2.14.0
      - networkx==3.6.1
      - numba==0.63.1
      - numexpr==2.14.1
      - numpy==1.26.4
      - oauthlib==3.3.1
      - onnxruntime==1.23.2
      - openai-whisper==20250625
      - opentelemetry-api==1.27.0
      - opentelemetry-exporter-otlp-proto-common==1.27.0
      - opentelemetry-exporter-otlp-proto-grpc==1.27.0
      - opentelemetry-proto==1.27.0
      - opentelemetry-sdk==1.27.0
      - opentelemetry-semantic-conventions==0.48b0
      - orjson==3.11.5
      - ormsgpack==1.12.1
      - overrides==7.7.0
      - packaging==23.2
      - pandas==2.3.3
      - pandas-gbq==0.32.0
      - patsy==1.0.2
      - pillow==10.4.0
      - posthog==7.4.2
      - propcache==0.4.1
      - proto-plus==1.27.0
      - protobuf==4.25.8
      - pulsar-client==3.8.0
      - pyarrow==22.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pydantic-settings==2.12.0
      - pydata-google-auth==1.9.1
      - pydeck==0.9.1
      - pynvim==0.6.0
      - pyparsing==3.2.5
      - pypika==0.48.9
      - python-dotenv==1.2.1
      - python-multipart==0.0.21
      - pytz==2025.2
      - pyyaml==6.0.3
      - referencing==0.37.0
      - regex==2025.11.3
      - requests==2.32.5
      - requests-oauthlib==2.0.0
      - requests-toolbelt==1.0.0
      - rich==13.9.4
      - rpds-py==0.30.0
      - rsa==4.9.1
      - safetensors==0.7.0
      - scikit-learn==1.8.0
      - scipy==1.16.3
      - seaborn==0.13.2
      - shapely==2.1.2
      - shellingham==1.5.4
      - smmap==5.0.2
      - sniffio==1.3.1
      - sqlalchemy==2.0.45
      - starlette==0.27.0
      - statsmodels==0.14.6
      - streamlit==1.28.0
      - sympy==1.14.0
      - tenacity==8.5.0
      - threadpoolctl==3.6.0
      - tiktoken==0.12.0
      - tokenizers==0.22.1
      - toml==0.10.2
      - torch==2.9.1
      - torchaudio==2.9.1
      - torchvision==0.24.1
      - tqdm==4.67.1
      - transformers==4.57.3
      - typer==0.21.0
      - typing-inspect==0.9.0
      - typing-inspection==0.4.2
      - tzdata==2025.3
      - tzlocal==5.3.1
      - uritemplate==4.2.0
      - urllib3==2.3.0
      - uuid-utils==0.12.0
      - uvicorn==0.24.0
      - uvloop==0.22.1
      - validators==0.35.0
      - watchdog==6.0.0
      - watchfiles==1.1.1
      - websocket-client==1.9.0
      - websockets==14.2
      - wrapt==2.0.1
      - xxhash==3.6.0
      - yarl==1.22.0
      - zipp==3.23.0
      - zstandard==0.25.0
prefix: /Users/kb/anaconda3/envs/msa
