name: sign_mvp
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5=7_kmp_llvm
  - aom=3.9.1=h7bae524_0
  - bzip2=1.0.8=h80987f9_6
  - c-ares=1.34.6=hc919400_0
  - ca-certificates=2025.12.2=hca03da5_0
  - cairo=1.18.0=hc6c324b_2
  - dav1d=1.2.1=hb547adb_0
  - expat=2.7.3=h50f4ffc_4
  - ffmpeg=7.1.0=gpl_h92f8dbd_105
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h1383a14_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - freetype=2.14.1=hce30654_0
  - fribidi=1.0.16=hc919400_0
  - gdk-pixbuf=2.42.12=h7ddc832_0
  - gmp=6.3.0=h7bae524_2
  - graphite2=1.3.14=hec049ff_2
  - harfbuzz=9.0.0=h1836168_0
  - hdf5=1.14.4=nompi_ha698983_105
  - icu=73.2=hc8870d7_0
  - imath=3.1.12=h025cafa_0
  - jasper=4.2.8=hc0e5025_0
  - krb5=1.21.3=h237132a_0
  - lame=3.100=h1a8c8d9_1003
  - lerc=4.0.0=hd64df32_1
  - libabseil=20240722.0=cxx17_h07bc746_4
  - libaec=1.1.4=h51d1e36_0
  - libasprintf=0.25.1=h493aca8_0
  - libass=0.17.3=hf20b609_0
  - libblas=3.11.0=5_h51639a9_openblas
  - libcblas=3.11.0=5_hb0561ab_openblas
  - libcurl=8.17.0=hdece5d2_1
  - libcxx=20.1.8=hd7fd590_1
  - libdeflate=1.22=hd74edd7_0
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libev=4.33=h93a5062_2
  - libexpat=2.7.3=h50f4ffc_4
  - libffi=3.4.4=hca03da5_1
  - libfreetype=2.14.1=hce30654_0
  - libfreetype6=2.14.1=h6da58f4_0
  - libgcc=15.2.0=hcbb3090_16
  - libgettextpo=0.25.1=h493aca8_0
  - libgfortran=15.2.0=h07b0088_16
  - libgfortran5=15.2.0=hdae7583_16
  - libglib=2.84.0=hdff4504_0
  - libhwloc=2.12.1=default_h88f92a7_1000
  - libiconv=1.18=h23cfdf5_2
  - libintl=0.25.1=h493aca8_0
  - libjpeg-turbo=3.1.2=hc919400_0
  - liblapack=3.11.0=5_hd9741b5_openblas
  - liblapacke=3.11.0=5_h1b118fd_openblas
  - libnghttp2=1.67.0=hc438710_0
  - libopenblas=0.3.30=openmp_ha158390_3
  - libopencv=4.10.0=headless_py310ha9432f1_12
  - libopenvino=2024.4.0=hbfeda7a_2
  - libopenvino-arm-cpu-plugin=2024.4.0=hbfeda7a_2
  - libopenvino-auto-batch-plugin=2024.4.0=hf276634_2
  - libopenvino-auto-plugin=2024.4.0=hf276634_2
  - libopenvino-hetero-plugin=2024.4.0=h03892cd_2
  - libopenvino-ir-frontend=2024.4.0=h03892cd_2
  - libopenvino-onnx-frontend=2024.4.0=h7f5a098_2
  - libopenvino-paddle-frontend=2024.4.0=h7f5a098_2
  - libopenvino-pytorch-frontend=2024.4.0=h5833ebf_2
  - libopenvino-tensorflow-frontend=2024.4.0=h9d544f2_2
  - libopenvino-tensorflow-lite-frontend=2024.4.0=h5833ebf_2
  - libopus=1.6=he530434_0
  - libpng=1.6.53=hfab5511_0
  - libprotobuf=5.28.2=h8f0b736_0
  - librsvg=2.58.4=h40956f1_0
  - libsqlite=3.51.1=h1b79a29_1
  - libssh2=1.11.1=h1590b86_0
  - libtiff=4.7.0=hfce79cd_1
  - libvpx=1.14.1=h7bae524_0
  - libwebp-base=1.6.0=h07db88b_0
  - libxml2=2.13.9=h528a072_0
  - libzlib=1.3.1=h5f15de7_0
  - llvm-openmp=21.1.8=h4a912ad_0
  - ncurses=6.5=hee39554_0
  - numpy=2.2.6=py310h4d83441_0
  - opencv=4.10.0=headless_py310h00e33b3_12
  - openexr=3.3.2=h04410fd_0
  - openh264=2.5.0=h774163f_0
  - openssl=3.6.0=h5503f6c_0
  - pango=1.54.0=h9ee27a3_2
  - pcre2=10.44=ha881caa_2
  - pip=25.3=pyhc872135_0
  - pixman=0.46.4=h81086ad_1
  - pugixml=1.14=h13dd4ca_0
  - py-opencv=4.10.0=headless_py310h87f01ad_12
  - python=3.10.15=hdce6c4c_2_cpython
  - python_abi=3.10=8_cp310
  - readline=8.3=h0b18652_0
  - setuptools=80.9.0=py310hca03da5_0
  - snappy=1.2.2=hada39a4_1
  - sqlite=3.51.0=hab6afd1_0
  - svt-av1=2.3.0=hf24288c_0
  - tbb=2022.3.0=h66ce52b_1
  - tk=8.6.15=hcd8a7d5_0
  - tzdata=2025b=h04d1e81_0
  - wheel=0.45.1=py310hca03da5_0
  - x264=1!164.3095=h57fd34a_2
  - x265=3.5=hbc6ce65_3
  - xz=5.6.4=h80987f9_1
  - zlib=1.3.1=h5f15de7_0
  - zstd=1.5.7=hbf9d68e_6
  - pip:
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - filelock==3.20.1
      - fsspec==2025.12.0
      - idna==3.11
      - jinja2==3.1.6
      - llvmlite==0.46.0
      - markupsafe==3.0.3
      - more-itertools==10.8.0
      - mpmath==1.3.0
      - networkx==3.4.2
      - numba==0.63.1
      - openai-whisper==20250625
      - pillow==12.0.0
      - regex==2025.11.3
      - requests==2.32.5
      - sympy==1.14.0
      - tiktoken==0.12.0
      - torch==2.9.1
      - torchaudio==2.9.1
      - torchvision==0.24.1
      - tqdm==4.67.1
      - typing-extensions==4.15.0
      - urllib3==2.6.2
prefix: /Users/kb/anaconda3/envs/sign_mvp
